import os

OPTIONS_FILE_PATH = "./options.chmd"

unprepared_dict = dict()
prepared_dict = dict()

GENERATED_CLI_OPTIONS_PATH = "./ChapterMD.Cli/Generated/Options.g.cs"
GENERATED_UTILS_PATH = "./ChapterMD.Cli/Generated/Utils.g.cs"
GENERATED_CORE_OPTIONS_PATH = "./ChapterMD.Core/Generated/WriterOptions.g.cs"

file_opened = open(OPTIONS_FILE_PATH).read().rstrip().lstrip().splitlines()


def read_unprepared():
    print(f"Reading {OPTIONS_FILE_PATH} ...")
    for i in range(0, file_opened.__len__()):
        if file_opened[i].startswith("#"):
            continue

        if file_opened[i].startswith("["):
            header = file_opened[i]
            variable = file_opened[i + 1]

            unprepared_dict[header] = variable


def prepare_dict():
    print("Setting up final dictionary ...")
    for k, v in unprepared_dict.items():
        attribute_clean = str(k).removeprefix("[").removesuffix("]").split(",")
        command = attribute_clean[0]
        help_text = attribute_clean[1]

        vs = str(v)

        half_split_index = vs.index(" = ")

        default = vs.replace(" ", "")[half_split_index:]

        first_half = vs[0:half_split_index]
        last_half = vs[half_split_index:]

        attribute = f"[Option({command}, Default = {default}, HelpText ={help_text})]"
        variable_code = f"public {first_half}" + " {get; set;}" + last_half + ";\n\n"

        prepared_dict[attribute] = variable_code


def create_dirs():
    print("Creating Generated dirs ...")
    os.makedirs(os.path.dirname(GENERATED_CLI_OPTIONS_PATH), exist_ok=True)
    os.makedirs(os.path.dirname(GENERATED_CORE_OPTIONS_PATH), exist_ok=True)
    os.makedirs(os.path.dirname(GENERATED_UTILS_PATH), exist_ok=True)


def generate(file_name: str, file_path: str, body: str, usesCommandLineParser=False):
    print(f"Generating {file_name} ...")

    with open(file_path, "w+") as f:

        f.write("""// <auto-generated>
//     This code was generated by an epic tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
""")

        f.write(
            f"\n\nnamespace {file_path[file_path.index('/')+1:file_path.index('/', 2)]};\n\n{"using CommandLine;\n\n" if usesCommandLineParser else ""}"
        )

        f.write(f"public partial class {file_name.split('.')[0]}" + " {\n\n")

        for k, v in prepared_dict.items():
            f.write(body.replace("{k}", k).replace("{v}", v))

        f.write("}")

    print("Alhamdulillah, Options.g.cs generation completed.")


def generate_utils():
    print("Generating Utils ...")

    with open(GENERATED_UTILS_PATH, "w+") as f:
        f.write("""
using ChapterMD.Core;

namespace ChapterMD.Cli;

public static partial class Utils
{
    public static WriterOptions ToWriterOptions(Options options)
    {
        return new WriterOptions
        {
""")

        for _, v in prepared_dict.items():
            vsplit = str(v).split(" ")
            f.write(f"\t\t\t{vsplit[2]} = options.{vsplit[2]},\n")

        f.write("""
            };
        }
    }

    """)


if __name__ == "__main__":
    read_unprepared()
    create_dirs()

    prepare_dict()

    # CLI Generate
    generate("Options.g.cs", GENERATED_CLI_OPTIONS_PATH, "\t{k}\n\t{v}", True)

    # Core Generate
    generate("WriterOptions.g.cs", GENERATED_CORE_OPTIONS_PATH, "\t{v}")

    generate_utils()

    print("All generation done.")
