import os

OPTIONS_FILE_PATH = "./options.txt"

unprepared_dict = dict()
prepared_dict = dict()

GENERATED_CLI_OPTIONS_PATH = "./ChapterMD.Cli/Generated/Options.g.cs"
GENERATED_UTILS_PATH = "./ChapterMD.Cli/Generated/Utils.g.cs"
GENERATED_CORE_OPTIONS_PATH = "./ChapterMD.Core/Generated/WriterOptions.g.cs"

file_opened = open(OPTIONS_FILE_PATH).read().rstrip().lstrip().splitlines()


def read_unprepared():
    print(f"Reading {OPTIONS_FILE_PATH} ...")
    i = 0

    while i < len(file_opened):
        line = file_opened[i].strip()

        if not line or line.startswith("#"):
            i += 1
            continue

        if line.startswith("["):
            attributes = []

            # Collect one or more consecutive attribute lines.
            while i < len(file_opened) and file_opened[i].strip().startswith("["):
                attributes.append(file_opened[i].strip())
                i += 1

            while i < len(file_opened):
                next_line = file_opened[i].strip()
                if not next_line or next_line.startswith("#"):
                    i += 1
                    continue
                break

            if i >= len(file_opened):
                break

            variable = file_opened[i].strip()
            unprepared_dict["\n".join(attributes)] = variable
            i += 1
        else:
            i += 1


def split_variable(vs: str):
    index = vs.index(" = ")

    first_half = vs[:index].strip()
    raw_default = vs[index + 3 :].strip()

    if raw_default.endswith(";"):
        raw_default = raw_default[:-1].rstrip()

    default = raw_default
    last_half = f" = {default}"

    return first_half, default, last_half


def prepare_dict():
    print("Setting up final dictionary ...")

    for k, v in unprepared_dict.items():
        first_half, default, last_half = split_variable(str(v))

        variable_code = f"public {first_half} {{get; set;}}{last_half};"

        # Old syntax:
        # ["file",,, "File name"]
        # string FileName = "Chapters.md"
        #
        # New syntax:
        # [CommandArgument(0, "<file-name>")]
        # [Description("File name")]
        # [DefaultValue("Chapters.md")]
        # string FileName = "Chapters.md"
        if ",,," in k and "\n" not in k:
            attribute_clean = k.removeprefix("[").removesuffix("]").split(",,,")
            command = attribute_clean[0]
            help_text = attribute_clean[1] if len(attribute_clean) > 1 else ""

            cli_attribute = (
                f"[Option({command}, Default = {default}, HelpText ={help_text})]"
            )
        else:
            cli_attribute = k

        prepared_dict[cli_attribute] = variable_code


def create_dirs():
    print("Creating Generated dirs ...")
    os.makedirs(os.path.dirname(GENERATED_CLI_OPTIONS_PATH), exist_ok=True)
    os.makedirs(os.path.dirname(GENERATED_CORE_OPTIONS_PATH), exist_ok=True)
    os.makedirs(os.path.dirname(GENERATED_UTILS_PATH), exist_ok=True)


def write_indented(f, text: str, indent: int = 1):
    prefix = "\t" * indent
    for line in text.splitlines():
        f.write(prefix + line + "\n")


def generate(file_name: str, file_path: str, body: str, usesSpectreConsole=False):
    print(f"Generating {file_name} ...")

    with open(file_path, "w+") as f:
        f.write("""// <auto-generated>
//     This code was generated by an epic tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
""")

        namespace = file_path[file_path.index("/") + 1 : file_path.index("/", 2)]

        f.write(f"\n\nnamespace {namespace};\n\n")
        if usesSpectreConsole:
            f.write("using Spectre.Console.Cli;\nusing System.ComponentModel;\n\n")

        f.write(f"public partial class {file_name.split('.')[0]} {{\n\n")

        for k, v in prepared_dict.items():
            entry = body.replace("{k}", k).replace("{v}", v)
            write_indented(f, entry, 1)
            f.write("\n")

        f.write("}")

    print(f"Alhamdulillah, {file_name} generation completed.")


def get_property_name(variable_code: str):
    before_braces = variable_code.split("{", 1)[0].strip()
    return before_braces.split()[-1]


def generate_utils():
    print("Generating Utils ...")

    with open(GENERATED_UTILS_PATH, "w+") as f:
        f.write("""
using ChapterMD.Core;

namespace ChapterMD.Cli;

public static partial class Utils
{
    public static WriterOptions ToWriterOptions(Options options)
    {
        return new WriterOptions
        {
""")

        for _, v in prepared_dict.items():
            property_name = get_property_name(str(v))
            f.write(f"\t\t\t{property_name} = options.{property_name},\n")

        f.write("""
            };
        }
    }

    """)


if __name__ == "__main__":
    read_unprepared()
    create_dirs()

    prepare_dict()

    # CLI Generate
    generate("Options.g.cs", GENERATED_CLI_OPTIONS_PATH, "{k}\n{v}", True)

    # Core Generate
    generate("WriterOptions.g.cs", GENERATED_CORE_OPTIONS_PATH, "{v}")

    generate_utils()

    print("All generation done.")
